name: Run CI checks

on:
  pull_request:
    branches:
      - "main"

  workflow_call:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # https://d2lang.com/tour/install/
    - name: Install D2
      run: |
        curl -fsSL https://d2lang.com/install.sh | sh -s --

    - name: Install bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
      
    - name: Install dependencies
      run: |
        bun install

    - name: Run check
      run: |
        bun run check
